name: modules to s3
on:
  push:
    branches:
    - dev
    - master
    paths:
    - app/modules/**
      
  workflow_dispatch:

jobs:
  zip-and-copy-to-s3:
    name: modules to s3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Zip modules
      run: zip -r modules.zip app/modules/
    - name: Copy to S3
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION}}
      run: |
        aws s3 cp modules.zip s3://bucket-name/folder/